platform :ios, '15.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # iOS min للخرائط وفايربيس الحديثة
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      # ✅ أجبر Swift 5
      config.build_settings['SWIFT_VERSION'] = '5.0'
      # ✅ خفّف تشدد Swift 6 Concurrency (يقلّبها لوضع متوافق)
      config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'minimal'
      # لا توقيع للـ Pods
      config.build_settings['CODE_SIGNING_ALLOWED']   = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED']  = 'NO'
      config.build_settings['CODE_SIGNING_IDENTITY']  = ''
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
      config.build_settings['DEVELOPMENT_TEAM'] = ''
      config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
    end
    # مهم: مرّر target (مو installer)
    flutter_additional_ios_build_settings(target)
  end
end

